export const characters = [
  { id: 1, name: 'Chris', gender: 'Male', hair: 'Black', eyes: 'Brown', glasses: false, hat: true, facialHair: 'None', row: 0, col: 0 },
  { id: 2, name: 'Nick', gender: 'Male', hair: 'Bald', eyes: 'Brown', glasses: true, hat: false, facialHair: 'None', row: 0, col: 1 },
  { id: 3, name: 'Kyle', gender: 'Male', hair: 'Blonde', eyes: 'Blue', glasses: false, hat: false, facialHair: 'None', row: 0, col: 2 },
  { id: 4, name: 'Daniel', gender: 'Male', hair: 'Black', eyes: 'Brown', glasses: false, hat: true, facialHair: 'None', row: 0, col: 3 },
  { id: 5, name: 'Rachael', gender: 'Female', hair: 'Brown', eyes: 'Brown', glasses: false, hat: true, facialHair: 'None', row: 0, col: 4 },
  { id: 6, name: 'Jake', gender: 'Male', hair: 'Blonde', eyes: 'Blue', glasses: false, hat: false, facialHair: 'Mustache', row: 0, col: 5 },
  { id: 7, name: 'Sarah', gender: 'Female', hair: 'Black', eyes: 'Brown', glasses: true, hat: false, facialHair: 'None', row: 1, col: 0 },
  { id: 8, name: 'Emily', gender: 'Female', hair: 'White', eyes: 'Brown', glasses: true, hat: false, facialHair: 'None', row: 1, col: 1 },
  { id: 9, name: 'Andy', gender: 'Male', hair: 'Black', eyes: 'Brown', glasses: false, hat: false, facialHair: 'None', row: 1, col: 2 },
  { id: 10, name: 'Tyler', gender: 'Male', hair: 'Black', eyes: 'Brown', glasses: false, hat: false, facialHair: 'Mustache', row: 1, col: 3 },
  { id: 11, name: 'Brandon', gender: 'Male', hair: 'Blonde', eyes: 'Brown', glasses: false, hat: true, facialHair: 'None', row: 1, col: 4 },
  { id: 12, name: 'James', gender: 'Male', hair: 'Bald', eyes: 'Brown', glasses: false, hat: false, facialHair: 'Beard', row: 1, col: 5 },
  { id: 13, name: 'Zachary', gender: 'Male', hair: 'Ginger', eyes: 'Brown', glasses: false, hat: false, facialHair: 'Mustache', row: 2, col: 0 },
  { id: 14, name: 'Jon', gender: 'Male', hair: 'White', eyes: 'Brown', glasses: false, hat: false, facialHair: 'Beard', row: 2, col: 1 },
  { id: 15, name: 'William', gender: 'Male', hair: 'Blonde', eyes: 'Brown', glasses: false, hat: false, facialHair: 'Beard', row: 2, col: 2 },
  { id: 16, name: 'Justin', gender: 'Male', hair: 'Brown', eyes: 'Brown', glasses: false, hat: false, facialHair: 'Mustache', row: 2, col: 3 },
  { id: 17, name: 'Joseph', gender: 'Male', hair: 'Red', eyes: 'Brown', glasses: true, hat: false, facialHair: 'None', row: 2, col: 4 },
  { id: 18, name: 'Connor', gender: 'Male', hair: 'Brown', eyes: 'Brown', glasses: false, hat: false, facialHair: 'Mustache', row: 2, col: 5 },
  { id: 19, name: 'Alex', gender: 'Male', hair: 'Grey', eyes: 'Brown', glasses: true, hat: false, facialHair: 'None', row: 3, col: 0 },
  { id: 20, name: 'Ashley', gender: 'Female', hair: 'Red', eyes: 'Brown', glasses: false, hat: true, facialHair: 'None', row: 3, col: 1 },
  { id: 21, name: 'Joshua', gender: 'Male', hair: 'White', eyes: 'Brown', glasses: false, hat: false, facialHair: 'Mustache', row: 3, col: 2 },
  { id: 22, name: 'Matt', gender: 'Male', hair: 'White', eyes: 'Brown', glasses: false, hat: false, facialHair: 'None', row: 3, col: 3 },
];
